export const GET_PRODUCT_ACTION = "GET_PRODUCT_ACTION";
export const CREATE_PRODUCT_ACTION = "CREATE_PRODUCT_ACTION";
export const GET_PRODUCT_BY_ID_ACTION = "GET_PRODUCT_BY_ID_ACTION";
export const UPDATE_PRODUCT_ACTION = "UPDATE_PRODUCT_ACTION";
export const DELETE_PRODUCT_ACTION = "DELETE_PRODUCT_ACTION";
export const GET_PRODUCT_ACTION_LOADING = "GET_PRODUCT_ACTION_LOADING";

export const FETCH_ACTION = "FETCH_ACTION";
export const FETCH_LOADING_ACTION = "FETCH_LOADING_ACTION";
export const FETCH_DETAIL_ACTION = "FETCH_DETAIL_ACTION";